# Find RtlSdr

FIND_PATH(RTLSDR_INCLUDE_DIR rtl-sdr.h)

SET(RTLSDR_NAMES ${RTLSDR_NAMES} rtlsdr librtlsdr librtlsdr.dll)
FIND_LIBRARY(RTLSDR_LIBRARY NAMES ${RTLSDR_NAMES} PATH)

IF (RTLSDR_INCLUDE_DIR AND RTLSDR_LIBRARY)
    SET(RTLSDR_FOUND TRUE)
ENDIF (RTLSDR_INCLUDE_DIR AND RTLSDR_LIBRARY)

IF (RTLSDR_FOUND)
    IF (NOT RTLSDR_FIND_QUIETLY)
        MESSAGE (STATUS "Found RTLSDR: ${RTLSDR_LIBRARY}")
    ENDIF (NOT RTLSDR_FIND_QUIETLY)
ELSE (RTLSDR_FOUND_FOUND)
    IF (RTLSDR_FIND_REQUIRED)
        MESSAGE (FATAL_ERROR "Could not find RTLSDR")
    ENDIF (RTLSDR_FIND_REQUIRED)
ENDIF (RTLSDR_FOUND)
